### PR TITLE
Fixed build error/added constexpr

### PR DESCRIPTION
**Pull request by vlocateli**
Fixed build error, added 
```c++
constexpr
``` 
to class member to make it compiler-time constant.

### CODE REVIEW

**Review by anderskaestner — CHANGES_REQUESTED** [review]
There is still something that breaks the windows build action.

**Comment by vlocateli** [comment]
Weird. Isn't because the MinGW compiler is interpreting `\openmp` and `\O2` as files?
```c++
c++.exe: warning: /openmp: linker input file unused because linking not done
c++.exe: warning: /O2: linker input file unused because linking not done
``` 
@anderskaestner

**Comment by vlocateli** [comment]
I think I know why it's failing, in Actions webpage, if you see h[ttps://github.com/neutronimaging/imagingsuite/actions/runs/9601626681/workflow](Actions Workflow file), the Windows compiler is set to CL but the errors show MinGW being used... 

```C++
-- The CXX compiler identification is GNU 12.2.0
[...]
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
```
The problem is using `cl` (Microsoft's Visual C++ Compiler) with GCC flags. That's why it fails, I think. @anderskaestner

**Comment by vlocateli** [comment]
@damskii9992 Could you change the Windows compiler to MinGW in the workflow file? :)

**Comment by anderskaestner** [comment]
> @damskii9992 Could you change the Windows compiler to MinGW in the workflow file? :)

I'd prefer adapting the compile arguments for msvc.

**Comment by vlocateli** [comment]
> > @damskii9992 Could you change the Windows compiler to MinGW in the workflow file? :)
> 
> I'd prefer adapting the compile arguments for msvc. But, good that you found the cause of the problem.

The problem is that MSVC uses an old version of OpenMP library from 2002. We can use the flags `/openmp:llvm` to use LLVM runtime with MSVC,  `/openmp:experimental` is also an option. See: [OpenMP support in MSVC](https://learn.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=msvc-170)

**Comment by anderskaestner** [comment]
I'm actually about to replace the openmp code with std:thread based implementations. See thread pool. So openmp will anyway be phased out.

**Comment by vlocateli** [comment]
> I'm actually about to replace the openmp code with std:thread based implementations. See thread pool. So openmp will anyway be phased out.

Can I help?

**Comment by damskii9992** [comment]
The broken Windows build seems to be due to visual studio changing how they version their software. I am currently looking into it.

**Review by anderskaestner — APPROVED** [review]

**Pull request merged**
